name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set tag timestamp env
      run: echo ::set-env name=TIMESTAMP::$(date +%F)
    - name: Set tag hash env
      run: echo ::set-env name=SHA::$(echo "${GITHUB_SHA}" | cut -c1-6)
    - name: Docker login
      run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Docker build
      run: docker build -t danielmurphy/kali-docker:latest .
    - name: Docker tag with date
      run: docker tag danielmurphy/kali-docker:latest danielmurphy/kali-docker:$TIMESTAMP-$SHA
    - name: Publish timestamped docker tag
      run: docker push danielmurphy/kali-docker:$TIMESTAMP-$SHA
    - name: Publish latest docker tag
      run: docker push danielmurphy/kali-docker:latest
