name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Authenticate to Github Package Registry
      run: docker login docker.pkg.github.com --username DanHatesNumbers --password ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/DanHatesNumbers/kali-docker:$(date +%s) --tag docker.pkg.github.com/DanHatesNumbers/kali-docker:latest
    - name: Publish Docker Image
      run: docker push docker.pkg.github.com/DanHatesNumbers/kali-docker:latest
